import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 DevOps',
      link: {type: 'doc', id: 'devops/intro'},
      items: [{type: 'autogenerated', dirName: 'devops'}],
    },
    {
      type: 'category',
      label: '⚙️ Backend',
      link: {type: 'doc', id: 'backend/intro'},
      items: [{type: 'autogenerated', dirName: 'backend'}],
    },
    {
      type: 'category',
      label: '🎨 Frontend',
      link: {type: 'doc', id: 'frontend/intro'},
      items: [{type: 'autogenerated', dirName: 'frontend'}],
    },
    {
      type: 'category',
      label: '📱 Mobile',
      link: {type: 'doc', id: 'mobile/intro'},
      items: [{type: 'autogenerated', dirName: 'mobile'}],
    },
    {
      type: 'category',
      label: '⛓️ Blockchain',
      link: {type: 'doc', id: 'blockchain/intro'},
      items: [{type: 'autogenerated', dirName: 'blockchain'}],
    },
    {
      type: 'category',
      label: '🤖 AI & Machine Learning',
      link: {type: 'doc', id: 'ai-ml/intro'},
      items: [{type: 'autogenerated', dirName: 'ai-ml'}],
    },
    {
      type: 'category',
      label: '💾 Database',
      link: {type: 'doc', id: 'database/intro'},
      items: [{type: 'autogenerated', dirName: 'database'}],
    },
    {
      type: 'category',
      label: '🎮 Games',
      link: {type: 'doc', id: 'games/intro'},
      items: [{type: 'autogenerated', dirName: 'games'}],
    },
    {
      type: 'category',
      label: '🔒 Security',
      link: {type: 'doc', id: 'security/intro'},
      items: [{type: 'autogenerated', dirName: 'security'}],
    },
    {
      type: 'category',
      label: '🧪 Testing',
      link: {type: 'doc', id: 'testing/intro'},
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      link: {type: 'doc', id: 'architecture/intro'},
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: '⚡ Performance',
      link: {type: 'doc', id: 'performance/intro'},
      items: [{type: 'autogenerated', dirName: 'performance'}],
    },
    {
      type: 'category',
      label: '🌐 Networking',
      link: {type: 'doc', id: 'networking/intro'},
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    {
      type: 'category',
      label: '☁️ Cloud',
      link: {type: 'doc', id: 'cloud/intro'},
      items: [{type: 'autogenerated', dirName: 'cloud'}],
    },
    {
      type: 'category',
      label: '🛠️ Tools',
      link: {type: 'doc', id: 'tools/intro'},
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: '🎨 Design',
      link: {type: 'doc', id: 'design/intro'},
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: '🌐 Useful Websites',
      link: {type: 'doc', id: 'websites/intro'},
      items: [{type: 'autogenerated', dirName: 'websites'}],
    },
    {
      type: 'category',
      label: '💼 Projects',
      link: {type: 'doc', id: 'projects/intro'},
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
  ],
};

export default sidebars;
